version: '3'

services:

  minio:
    container_name: minio_polars
    image: minio/minio
    hostname: minio
    ports: 
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    networks:
      - netpol
    volumes:
      - ./lakehouse:/data
    command: server /data --console-address ":9001"
  
networks:
  netpol:
    name: network_polars
    driver: bridge